### ISSUE TITLE
Electron app does not open after restarting.

### ISSUE THREAD

**Issue by Shakib1126** [ogra1/electron-kiosk-simplified#1]
I have built my electon kiosk for ubuntu following all your steps. i have completed building a snap for it and also tested it using  " snap run " command. But after i restart or poweroff my system, the application does not launch on boot. Means its still not a kisok ubuntu app. 

NOTE : I have kept confinement as " devmode " in the entire process. Does this have something to do with above problem?

**Comment by ogra1** [comment]
```snap run``` is not supposed to work at all since this snap is designed as a daemon ... can you point me to your snapcraft.yaml ? also make sure that mir-kiosk is properly up and running and you have connected all necessary snap interfaces, without these the snap can not start  ...

EDIT: oops, i just noticed your note on "devmode" above ... with devmode set the interfaces are indeed not a hard requirement (though your logs will be flooded with messages then) ... but you will still need a wayland compositor like mir-kiosk running that the snap can consume nontheless ...

**Comment by Shakib1126** [comment]
```
name: electron-hello-world-kiosk
version: '0.1'
summary: Hello World Electron app for a Kiosk
description: |
  Simple Hello World Electron app as an example of a HTML5 Kiosk
base: core18
confinement: devmode
grade: devel
compression: lzo

apps:
  electron-hello-world-kiosk:
    daemon: simple
    extensions: [ gnome-3-28 ]
    restart-condition: always
    command: desktop-launch xwayland-kiosk-launch $SNAP/electron-helloworld/electron-quick-start --no-sandbox
    plugs:
      - browser-support
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland

layout:
  /usr/share/fonts:
    bind: $SNAP/usr/share/fonts

environment:
  XWAYLAND_FULLSCREEN_WINDOW_HINT: window_role="browser-window"

parts:
  electron-helloworld:
    plugin: nodejs
    source: .
    override-build: |
      npm install electron-packager
      ./node_modules/.bin/electron-packager . --overwrite \
          --platform=linux --output=release-build --prune=true
      cp -v -R ./electron-linux-x64 $SNAPCRAFT_PART_INSTALL/electron-helloworld
    stage-packages:
      - libnspr4
      - libnss3
    build-snaps:
      - node/14/stable

    build-environment:
      - PATH: /snap/bin:$PATH

  xwayland-kiosk-helper:
    plugin: cmake
    source: https://github.com/MirServer/xwayland-kiosk-helper.git
    build-packages: [ build-essential ]
    stage-packages: [ xwayland, i3, libegl1-mesa, libgl1-mesa-glx ]

```

here is my entire snapcraft.yaml file.
i also get this error when i run the snap for testing. My app opens after the "snap run electron-hello-world-kiosk " command but it also shows the below error


```
_XSERVTransSocketCreateListener: failed to bind listener
_XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
_XSERVTransMakeAllCOTSServerListeners: failed to create listener for unix
glamor: EGL version 1.4:
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Error:            Illegal keycode 569 (must be in the range 8-255 inclusive)
>                   Value of "maximum" not changed
> Error:            Illegal keycode 372 for name <I372>
>                   Must be in the range 8-255 inclusive
> Error:            Illegal keycode 380 for name <I380>
>                   Must be in the range 8-255 inclusive
> Error:            Illegal keycode 382 for name <I382>
>                   Must be in the range 8-255 inclusive
> Error:            Illegal keycode 569 for name <I569>
>                   Must be in the range 8-255 inclusive
Errors from xkbcomp are not fatal to the X server

```
